### ISSUE TITLE
Combine upload and mustachify actions into a single button click

### ISSUE THREAD

**Issue by schloo** [RagtagOpen/mustachify#18]
UI has been updated with this change already

**Comment by iandees** [comment]
I added back a button to submit the form in #19 before I saw this. The only way we'll be able to do this is with JavaScript (by having javascript hit the submit button when the user selects an image). @schloo, can you update the style so that the button matches the rest of the page?

![image](https://user-images.githubusercontent.com/261584/34910804-2bdcaa2a-f882-11e7-86e9-05606618a244.png)

With that styling fix, I can add the JavaScript to submit the form when the user selects an image.

**Comment by schloo** [comment]
@iandees Even if the button exists, can I make the button invisible?

**Comment by bnd5k** [comment]
PR: https://github.com/RagtagOpen/mustachify/issues/18

**Comment by iandees** [comment]
I think this was fixed in #23.
