### ISSUE TITLE
Result image doesn't always fit in campaign's iframe

### ISSUE THREAD

**Issue by jillh510** [RagtagOpen/mustachify#52]
The campaign's idea is to embed the tool in an iframe on a page like this: https://secure.randybryceforcongress.com/page/s/stache-yo-self

The attached image is too tall within the iframe once it's mustachified, leaving the buttons off the bottom:
![salman_monday2](https://user-images.githubusercontent.com/2319837/38513670-c369e1f6-3be3-11e8-9f52-7f8a4c107004.JPG)

 (screenshot)

![screen shot 2018-04-09 at 10 50 40 am](https://user-images.githubusercontent.com/2319837/38513691-d7b254fe-3be3-11e8-9443-c1304671228f.png)

**Comment by dryan** [comment]
This is fixed by the responsive changes just merged in. We'll need to update their embed code to use `<script src="http://ironstache.herokuapp.com/static/js/embed.js"></script>` in place of the `<iframe>` they have now.

They should really put the embed on a page after the initial signup form stuff is collected.

**Comment by jillh510** [comment]
fixed by the campaign using the <script> tag
